name: quantity_input
description: A simple widget to help you handle quantity inputs with formatted value
version: 1.0.0
homepage: https://github.com/4inka/flutter_quantity_input

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
